baseurl = "/"
languageCode = "en-us"
title = "Classic"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Powered by [Hugo](https://gohugo.io/) | [Classic Theme](https://themes.gohugo.io/hugo-classic/) | Blog by [Greg Babb](https://twitter.com/grbabb)"
    custom_css = ["css/theme-override.css"]
